"""Stable error codes for API responses."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INVALID_PATH = "INVALID_PATH"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    PARAGRAPH_INDEX_OUT_OF_RANGE = "PARAGRAPH_INDEX_OUT_OF_RANGE"
    SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND"
    STYLE_NOT_FOUND = "STYLE_NOT_FOUND"
    CONFLICT = "CONFLICT"
    DOCX_ERROR = "DOCX_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
